workflows:
  sample-workflow:
    environment:
      flutter: stable
  android-workflow-id:
    name: Android Sample Workflow
    # .......
    # .......
    # .......
  ios-workflow-id:
    name: iOS Sample Workflow
    # ......