name: projeto_flutter
description: "A new Flutter project with Firebase."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  google_sign_in: ^6.0.0
  cloud_firestore: ^5.4.4
  firebase_messaging: 15.1.3   # Adiciona o firebase_messaging para notificações push
  font_awesome_flutter: ^10.0.0
  flutter_facebook_auth: ^5.0.1   # Adiciona suporte ao Facebook
  sign_in_with_apple: ^4.0.0  # Adicione esta linha


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
