// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:firebase_auth/firebase_auth.dart';
import 'firebase_options.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrSOuIvuPghzt9j39Pimve9Mgggl0WcLY',
    appId: '1:951661727125:web:91c6c2cb47116956f17a9c',
    messagingSenderId: '951661727125',
    projectId: 'projeto-teste-f8891',
    authDomain: 'projeto-teste-f8891.firebaseapp.com',
    databaseURL: 'https://projeto-teste-f8891-default-rtdb.firebaseio.com',
    storageBucket: 'projeto-teste-f8891.appspot.com',
    measurementId: 'G-FH1M4KM8HG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJ0fraQ9rfYrr1-ditk06fNZBI6BfrCFg',
    appId: '1:951661727125:android:ccd62e6048aaca0cf17a9c',
    messagingSenderId: '951661727125',
    projectId: 'projeto-teste-f8891',
    databaseURL: 'https://projeto-teste-f8891-default-rtdb.firebaseio.com',
    storageBucket: 'projeto-teste-f8891.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYRlSsfumQXKW8f-auXtFJKQJM1Q086Ls',
    appId: '1:951661727125:ios:ee685de6d40944adf17a9c',
    messagingSenderId: '951661727125',
    projectId: 'projeto-teste-f8891',
    databaseURL: 'https://projeto-teste-f8891-default-rtdb.firebaseio.com',
    storageBucket: 'projeto-teste-f8891.appspot.com',
    iosBundleId: 'com.example.projetoFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYRlSsfumQXKW8f-auXtFJKQJM1Q086Ls',
    appId: '1:951661727125:ios:ee685de6d40944adf17a9c',
    messagingSenderId: '951661727125',
    projectId: 'projeto-teste-f8891',
    databaseURL: 'https://projeto-teste-f8891-default-rtdb.firebaseio.com',
    storageBucket: 'projeto-teste-f8891.appspot.com',
    iosBundleId: 'com.example.projetoFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrSOuIvuPghzt9j39Pimve9Mgggl0WcLY',
    appId: '1:951661727125:web:65d0d224c477a98af17a9c',
    messagingSenderId: '951661727125',
    projectId: 'projeto-teste-f8891',
    authDomain: 'projeto-teste-f8891.firebaseapp.com',
    databaseURL: 'https://projeto-teste-f8891-default-rtdb.firebaseio.com',
    storageBucket: 'projeto-teste-f8891.appspot.com',
    measurementId: 'G-FJKG9L71WV',
  );

}